---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    app.kubernetes.io/name: facebook-clone
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    app.kubernetes.io/name: facebook-clone
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    purpose: observability
