from __future__ import annotations

from typing import Protocol, runtime_checkable

from fb.domain.shared.entity_id import EntityId
from fb.domain.post.comment import Comment


@runtime_checkable
class CommentRepository(Protocol):
    async def find_by_id(self, comment_id: EntityId) -> Comment | None: ...
    async def save(self, comment: Comment) -> Comment: ...
    async def delete(self, comment_id: EntityId) -> None: ...
    async def find_by_post(self, post_id: EntityId, limit: int = 20, offset: int = 0) -> list[Comment]: ...
    async def count_by_post(self, post_id: EntityId) -> int: ...