from __future__ import annotations

from typing import Protocol, runtime_checkable

from fb.domain.shared.entity_id import EntityId
from fb.domain.post.like import Like


@runtime_checkable
class LikeRepository(Protocol):
    async def find_by_post_and_user(self, post_id: EntityId, user_id: EntityId) -> Like | None: ...
    async def save(self, like: Like) -> Like: ...
    async def delete(self, like_id: EntityId) -> None: ...
    async def count_by_post(self, post_id: EntityId) -> int: ...
    async def find_by_post(self, post_id: EntityId, limit: int = 20, offset: int = 0) -> list[Like]: ...