from __future__ import annotations

from typing import Protocol, runtime_checkable

from fb.domain.shared.entity_id import EntityId
from fb.domain.post.reaction import Reaction, ReactionType


@runtime_checkable
class ReactionRepository(Protocol):
    async def save(self, reaction: Reaction) -> Reaction: ...
    async def find_by_post_and_user(self, post_id: EntityId, user_id: EntityId) -> Reaction | None: ...
    async def delete(self, reaction_id: EntityId) -> None: ...
    async def find_by_post(self, post_id: EntityId, limit: int = 20, offset: int = 0) -> list[Reaction]: ...
    async def count_by_post(self, post_id: EntityId) -> int: ...
    async def count_by_type(self, post_id: EntityId) -> dict[ReactionType, int]: ...
