from __future__ import annotations

from typing import Protocol, runtime_checkable
from fb.domain.shared.entity_id import EntityId
from fb.domain.post.entities import Post


@runtime_checkable
class PostRepository(Protocol):
    async def find_by_id(self, post_id: EntityId) -> Post | None: ...
    async def save(self, post: Post) -> Post: ...
    async def update(self, post: Post) -> Post: ...
    async def delete(self, post_id: EntityId) -> None: ...
    async def find_by_author(self, author_id: EntityId, limit: int = 20, offset: int = 0) -> list[Post]: ...
    async def count_by_author(self, author_id: EntityId) -> int: ...