from __future__ import annotations

from typing import Protocol, runtime_checkable

from fb.domain.shared.entity_id import EntityId
from fb.domain.post.share import Share


@runtime_checkable
class ShareRepository(Protocol):
    async def save(self, share: Share) -> Share: ...
    async def find_by_id(self, share_id: EntityId) -> Share | None: ...
    async def delete(self, share_id: EntityId) -> None: ...
    async def find_by_post(self, post_id: EntityId, limit: int = 20, offset: int = 0) -> list[Share]: ...
    async def count_by_post(self, post_id: EntityId) -> int: ...
